version: '2'

services:

  api:
    build: ./api
    depends_on:
      - postgres
    links:
      - postgres
    volumes:
      - ./api:/var/www/html
    ports:
      - "9000:9000"
  api-tests:
      image: binarydata/phpunit # our PHPUnit image, created or found on Docker Hub
      volumes:
        - ./api:/var/www/html
        - /tmp/:/tmp/ # linking /tmp/ folder because PHPStorm stores its stuff there
      depends_on:
        - postgres
      links:
        - postgres
  nginx:
    image: nginx:latest
    volumes:
      - ./conf/nginx/api.conf:/etc/nginx/conf.d/default.conf
    volumes_from:
      - api
    depends_on:
      - api
    links:
      - api
    ports:
      - "8890:80"
    command: nginx -g 'daemon off;'

  postgres:
    image: postgres:9.5
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=frida_wall
      - POSTGRES_PASSWORD=frida_wall
      - POSTGRES_DB=frida_wall